### ISSUE TITLE
Wrong weekday

### ISSUE THREAD

**Issue by almoloo** [AliRezaBeigy/react-native-global-datetimepicker#1]
<img width="241" alt="Screenshot 2024-01-03 at 14 01 42" src="https://github.com/AliRezaBeigy/react-native-global-datetimepicker/assets/2190300/36516a52-3552-46ee-8feb-a3ec8b0a7d05">

As you can see, the picker is calculating that 13/10/1402 is a Tuesday while it's Wednesday.

**Comment by AliRezaBeigy** [comment]
Hi ali
Thanks for the bug report
I will check this out today

**Comment by AliRezaBeigy** [comment]
Hey there
Good news, The bug you found with the date picker is now fixed
Thanks for catching that
If you spot anything else, just give us a shout
